###
# Values declared PROVIDED_AT_RUNTIME are populated from the workflow context.
###


# Used only for the spark application name
appName: Map build (dev)

source: PROVIDED_AT_RUNTIME

# The base directory into which HFiles will be stored
targetDirectory: PROVIDED_AT_RUNTIME

# The max record count allowed before the view is built into a tile pyramid
tilesThreshold: 100000

# HBase details
hbase:
  zkQuorum: PROVIDED_AT_RUNTIME
  rootDir: /hbase
  restoreDir: hdfs://nameservice1/tmp
  keySaltModulus: 10


# Applies only to those map views that have few enough records to be stored as features
pointFeatures:
  numTasks: 200 # controls the parallelism
  tableName: PROVIDED_AT_RUNTIME
  hfileCount: 32

# TilePyramid applies to views where there are more records than the tilesThreshold
# Notes:
#   For hfileCount > 32 you must use -Dhbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily=XXX when bulk loading
tilePyramid:
  tableName: PROVIDED_AT_RUNTIME
  hfileCount: 100
  numPartitions: 200
  tileBufferSize: 64
  projections:
    # Web Mercator (i.e. like Google maps)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3857
    # WGS84 Equirectangular
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:4326
    # North Pole LAEA Europe (i.e. Arctic)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3575
    # Antarctic Polar Stereographic (i.e. South pole)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3031
