# Used only for the spark application name
appName: Map build (development)

# An HBase snapshot table name, or a parquet file of occurrence records
# Hint: Consider using a Hive CTAS query "STORED AS PARQUET" from occurrence_hdfs
#source: /user/hive/warehouse/tim.db/occurrence_map_source_tenth

# hbase shell> snapshot 'dev_occurrence', 'dev_occurrence_20171115_1419'
source: dev_occurrence_20171115_1419

# The base directory into which HFiles will be stored
targetDirectory: hdfs://ha-nn/tmp/matt_test

# The max record count allowed before the view is built into a tile pyramid
tilesThreshold: 100000

# HBase details
hbase:
  zkQuorum: c3zk1.gbif-dev.org,c3zk2.gbif-dev.org,c3zk3.gbif-dev.org
  rootDir: /hbase
  keySaltModulus: 10

# Applies only to those map views that have few enough records to be stored as features
pointFeatures:
  numTasks: 200 # controls the parallelism
  tableName: matt_test
  hfileCount: 32

# TilePyramid applies to views where there are more records than the tilesThreshold
# Notes:
#   For hfileCount > 32 you must use -Dhbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily=XXX when bulk loading
tilePyramid:
  tableName: matt_test
  hfileCount: 100
  numPartitions: 200
  tileBufferSize: 64
  projections:
    # Web Mercator (i.e. like Google maps)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3857
    # WGS84 Equirectangular
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:4326
    # North Pole LAEA Europe (i.e. Arctic)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3575
    # Antarctic Polar Stereographic (i.e. South pole)
    -  minZoom: 0
       maxZoom: 16
       tileSize: 512
       srs: EPSG:3031

# Hdfs Lock to snapshot the avro hdfsview directory
hdfsLockConfig:
  zkConnectionString: PROVIDED_AT_RUNTIME
  namespace: prod_index_lock
  lockingPath: /hive/
  lockName: hdfsview
  sleepTimeMs: 100
  maxRetries: 5
